export const concerts = [
  {
    id: 1,
    title: 'Nora Bayas',
    category: 'Hip Hop & R&B',
    date: 'Aug 5, 2025',
    location: 'Scottsdale, AZ',
    persons: 124,
    price: 779.58,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=300&fit=crop',
    description: 'An unforgettable night of Hip Hop and R&B classics.',
    available_tickets: 50,
  },
  {
    id: 2,
    title: 'Tony Bennett',
    category: 'Jazz & Blues',
    date: 'Sep 14, 2025',
    location: 'New York, NY',
    persons: 89,
    price: 500.69,
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    description: 'A classic jazz evening with legendary performances.',
    available_tickets: 30,
  },
  {
    id: 3,
    title: 'Joan Baez',
    category: 'Folk',
    date: 'Oct 22, 2025',
    location: 'Nashville, TN',
    persons: 210,
    price: 405.27,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=300&fit=crop',
    description: 'Folk music at its finest in a beautiful outdoor venue.',
    available_tickets: 100,
  },
  {
    id: 4,
    title: 'Devendra Banhart',
    category: 'Alternative',
    date: 'Nov 1, 2025',
    location: 'Renfrew, CA',
    persons: 76,
    price: 275.43,
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=400&h=300&fit=crop',
    description: 'An intimate alternative music experience.',
    available_tickets: 40,
  },
];

export const shows = [
  {
    id: 5,
    title: "Slave's Snow",
    category: 'Theatre',
    date: 'Aug 5, 2025',
    location: 'Colorado',
    persons: 55,
    price: 473.65,
    image: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=400&h=300&fit=crop',
    description: 'A breathtaking theatrical snow show.',
    available_tickets: 20,
  },
  {
    id: 6,
    title: 'Flying Trapeze',
    category: 'Circus',
    date: 'Sep 10, 2025',
    location: 'Miami, FL',
    persons: 300,
    price: 797.50,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    description: 'Death-defying aerial acrobatics live!',
    available_tickets: 80,
  },
  {
    id: 7,
    title: 'Amaluma',
    category: 'Dance',
    date: 'Aug 20, 2025',
    location: 'Seka Mirova',
    persons: 90,
    price: 376.28,
    image: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400&h=300&fit=crop',
    description: 'A mesmerizing dance performance from around the world.',
    available_tickets: 60,
  },
  {
    id: 8,
    title: 'Fire of Anatolia',
    category: 'Cultural',
    date: 'Dec 3, 2025',
    location: 'La Porte',
    persons: 150,
    price: 120.65,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
    description: 'A spectacular fire and dance show from Turkey.',
    available_tickets: 200,
  },
];

export const sports = [
  {
    id: 9,
    title: 'Football',
    category: 'Team Sport',
    date: 'Aug 15, 2025',
    location: 'Los Angeles',
    persons: 500,
    price: 156.58,
    image: 'https://images.unsplash.com/photo-1551958219-acbc595b7c1f?w=400&h=300&fit=crop',
    description: 'Championship football match with top teams.',
    available_tickets: 500,
  },
  {
    id: 10,
    title: 'Hockey',
    category: 'Team Sport',
    date: 'Sep 5, 2025',
    location: 'Chicago, IL',
    persons: 220,
    price: 279.78,
    image: 'https://images.unsplash.com/photo-1487466365202-1afdb86c764e?w=400&h=300&fit=crop',
    description: 'Ice hockey at its most thrilling.',
    available_tickets: 150,
  },
  {
    id: 11,
    title: 'Karting',
    category: 'Motorsport',
    date: 'Oct 12, 2025',
    location: '8 Lanterns',
    persons: 45,
    price: 948.55,
    image: 'https://images.unsplash.com/photo-1526281014887-7e9c6e8b4f1f?w=400&h=300&fit=crop',
    description: 'High-speed karting competition.',
    available_tickets: 30,
  },
  {
    id: 12,
    title: 'Basketball',
    category: 'Team Sport',
    date: 'Nov 20, 2025',
    location: 'Seattle',
    persons: 350,
    price: 762.01,
    image: 'https://images.unsplash.com/photo-1546519638405-a9f9a0db0b49?w=400&h=300&fit=crop',
    description: 'NBA-level basketball excitement.',
    available_tickets: 200,
  },
];

export const festivals = [
  {
    id: 13,
    title: 'La Tomatina',
    category: 'Food & Drink',
    date: 'Aug 28, 2025',
    location: 'Buñol, Spain',
    persons: 1000,
    price: 600.65,
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=300&fit=crop',
    description: "Spain's famous tomato-throwing festival.",
    available_tickets: 400,
  },
  {
    id: 14,
    title: 'Aquacolor',
    category: 'Colour Festival',
    date: 'Sep 15, 2025',
    location: 'Torino, IT',
    persons: 600,
    price: 825.41,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    description: 'A vibrant water and colour festival.',
    available_tickets: 250,
  },
  {
    id: 15,
    title: 'Holwaze',
    category: 'Music Festival',
    date: 'Oct 31, 2025',
    location: 'Austin, TX',
    persons: 800,
    price: 843.65,
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=300&fit=crop',
    description: 'Multi-day music and arts festival.',
    available_tickets: 600,
  },
  {
    id: 16,
    title: 'Cultura Viva',
    category: 'Cultural',
    date: 'Dec 5, 2025',
    location: 'Montevideo',
    persons: 400,
    price: 820.44,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=300&fit=crop',
    description: 'A celebration of South American culture and art.',
    available_tickets: 300,
  },
];

export const topSingers = [
  { id: 1, name: 'Drake', location: 'Toronto, Canada', image: './assetes/drake.jpg' },
  { id: 2, name: 'Taylor Swift', location: 'Nashville, TN', image: './assetes/Taylor Swift.jpg' },
  { id: 3, name: 'Ed Sheeran', location: 'Halifax, England', image: './assetes/ed.jpg' },
  { id: 4, name: 'Billie Eilish', location: 'Los Angeles, CA', image: './assetes/Billie Eilish.jpg' },
  { id: 5, name: 'Adele', location: 'London, UK', image: './assetes/adele.jpg' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Jerome Bell',
    rating: 5,
    text: 'Absolutely amazing platform! Found tickets to my favorite artist instantly. The booking process was seamless and secure.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&h=50&fit=crop',
  },
  {
    id: 2,
    name: 'Wade Warren',
    rating: 5,
    text: 'Vestibulum ut lorem nec neque faucibus finibus. Sed porta commodo Blandit. Donec sit amet ultrices.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&h=50&fit=crop',
  },
  {
    id: 3,
    name: 'Annette Cooper',
    rating: 4,
    text: 'In a bid time, Magis Fusce dolor eu ullamcorper. Mauris quis aliquam elit. Mauris thit ac ulla.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop',
  },
  {
    id: 4,
    name: 'Brooklyn Simmons',
    rating: 5,
    text: 'The refundable ticket feature gives me complete peace of mind. I book for every major event now without hesitation!',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=50&h=50&fit=crop',
  },
];

export const faqs = [
  { q: 'When Does Private Market for Event-goer turn Open/Available?', a: 'Private market opens 7 days before the public sale date for all verified members.' },
  { q: 'Do you have subscription with that I purchased?', a: 'Yes, subscriptions are available with special benefits for premium ticket holders.' },
  { q: 'Why Must You have Share it before?', a: 'Sharing helps us verify event attendance and ensures your tickets reach you safely.' },
  { q: "I haven't received a reply. What should I do?", a: 'Please check your spam folder first, then contact our support team directly via chat.' },
  { q: 'Your Most Query and more Share for Ticket?', a: 'You can always manage your tickets from your account dashboard under "My Tickets."' },
];

export const allEventsForDropdown = [
  ...concerts.map(e => ({ id: e.id, title: e.title })),
  ...shows.map(e => ({ id: e.id, title: e.title })),
  ...sports.map(e => ({ id: e.id, title: e.title })),
  ...festivals.map(e => ({ id: e.id, title: e.title })),
];
